### PR TITLE
Implement Any support

### LINKED ISSUE #44: Consider crossover similar to "Copy" mutation.

### PR DESCRIPTION
**Pull request by vitalybuka**
Fixed #44, #151

### CODE REVIEW

**Comment by vitalybuka** [comment]
@asraa @htuch This is Any support.
User should do stuff like this: https://github.com/google/libprotobuf-mutator/pull/156/files#diff-7e1fb0213ba7bfbcc2935425ce018102R31-R46

**Comment by asraa** [comment]
> @asraa @htuch This is Any support.
> User should do stuff like this: https://github.com/google/libprotobuf-mutator/pull/156/files#diff-7e1fb0213ba7bfbcc2935425ce018102R31-R46

I patched this PR in for testing my fuzzer, and it seems like I can reproduce a crash so long as I add an appropriate corpus entry with the embedded `Any` in the expanded format (with the `[type.google.com/...] { <EXPANDED_PROTOBUF> }`. Seems like the way to go would then be to populate the corpus with valid configurations rather than using a dictionary for serialized protobufs strings. Thank you so much!

**Comment by vitalybuka** [comment]
> I'm a little uncertain that the fuzzer is able to mutate the message successfully. I'm seeing the fuzzer pick up the config I placed in the corpus. I then added a simple crash if the int in the Any message is different than the int I placed in the corpus entry, and have yet to crash on that. I'll keep checking.

It should mutate stuff inside of Any.
Here in example it expect string inside of any is not empty:
https://github.com/google/libprotobuf-mutator/pull/156/files#diff-7e1fb0213ba7bfbcc2935425ce018102R31-R46

Even more, it should mutate nested Any inside of Any, e.g. in unit-test we have:
const char kOptionalInDeepAnyFields[] = R"(
  any {
    [type.googleapis.com/protobuf_mutator.Msg] {
      any {
        [type.googleapis.com/protobuf_mutator.Msg] {
          any {
            [type.googleapis.com/protobuf_mutator.Msg] {
              optional_double: 1.9317850152856e-314
              optional_sint64: 1743625000076
              optional_string: "XYZ"
            }
          }
        }
      }
    }
  }
)";

If this is not the case, I'd like to check reproducer.
Also make sure that "-max_len=" is reasonable enough

**Comment by vitalybuka** [comment]
> I patched this PR in for testing my fuzzer, and it seems like I can reproduce a crash so long as I add an appropriate corpus entry with the embedded `Any` in the expanded format (with the `[type.google.com/...] { <EXPANDED_PROTOBUF> }`. Seems like the way to go would then be to populate the corpus with valid configurations rather than using a dictionary for serialized protobufs strings.
> 
Dictionary or corpus can be useful, however they don't let you run fuzzer binary on it's own.
So callback probably is more useful

I would like to add some type discovery mechanism. All protos should be already compiled in into fuzzer. However stuff I tried does not work. E.g. I expected to get types from https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor_database#DescriptorPoolDatabase, but FindAllMessageNames is not implemented there. It would be nice to have something like this.

**Comment by vitalybuka** [comment]
+ @hctim

**Comment by asraa** [comment]
@vitalybuka I debugged, and found the type_url that I set in the post-processor was setting the protobuf descriptor without the `type.googleapis.com/`. It works perfectly now! I'm assuming the mutator was not able to understand the type_url here 
`if (!Any::ParseAnyTypeUrl(any.type_url(), &type_name)) return nullptr`

**Comment by vitalybuka** [comment]
> @vitalybuka I debugged, and found the type_url that I set in the post-processor was setting the protobuf descriptor without the `type.googleapis.com/`. It works perfectly now! I'm assuming the mutator was not able to understand the type_url here
> `if (!Any::ParseAnyTypeUrl(any.type_url(), &type_name)) return nullptr`

Correct. That's how Any parses it's type.

**Pull request merged**
